CREATE TABLE HumanRobot (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	category varchar(255) not null,
	uri varchar(255) NULL,
	status varchar(255) DEFAULT 'NOT CREATED',
	available_date DATE,
	produced_date DATE,
	build_date DATE,
	stock_date DATE,
	price DOUBLE ,
	currency varchar(255),
	location varchar(255) DEFAULT 'CHINA',
	product_id varchar(255) not null,
	quality_check varchar(3) DEFAULT 'NO',
	creator varchar(255),
  tech_raw_creation_date DATE

);

create sequence human_sequence start with 1 increment by 1;

insert into HumanRobot (name, category,uri,status,available_date,produced_date,price,currency,location,product_id,quality_check)
                values ('IRobot', 'KidsRobot',null,'PRODUCED','2017-11-25','2017-11-11',152,'EUR',null,'HumanRobotkidsRobot125112018','OK');
